services:
  compras:
    image: elixir:otp-27-alpine
    container_name: compras
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      SERVER_TO_RUN: Libremarket.Compras.Server
      MIX_HOME: /app/mix_home
      HEX_HOME: /app/hex_home
      CLOUDAMQP_URL: ${CLOUDAMQP_URL}
    command: iex --sname compras --cookie secret -S mix run --no-compile
    stdin_open: true
    tty: true
    user: "${DOCKER_UID}:${DOCKER_GID}"

  infracciones:
    image: elixir:otp-27-alpine
    container_name: infracciones
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      SERVER_TO_RUN: Libremarket.Infracciones.Server
      MIX_HOME: /app/mix_home
      HEX_HOME: /app/hex_home
      CLOUDAMQP_URL: ${CLOUDAMQP_URL}
    command: iex --sname infracciones --cookie secret -S mix run --no-compile
    # para habilitar -it
    stdin_open: true
    tty: true
    user: "${DOCKER_UID}:${DOCKER_GID}"

  ventas:
    image: elixir:otp-27-alpine
    container_name: ventas
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      SERVER_TO_RUN: Libremarket.Ventas.Server
      MIX_HOME: /app/mix_home
      HEX_HOME: /app/hex_home
      CLOUDAMQP_URL: ${CLOUDAMQP_URL}
    command: iex --sname ventas --cookie secret -S mix run --no-compile
    # para habilitar -it
    stdin_open: true
    tty: true
    user: "${DOCKER_UID}:${DOCKER_GID}"

  envios:
    image: elixir:otp-27-alpine
    container_name: envios
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      SERVER_TO_RUN: Libremarket.Envios.Server
      MIX_HOME: /app/mix_home
      HEX_HOME: /app/hex_home
      CLOUDAMQP_URL: ${CLOUDAMQP_URL}
    command: iex --sname envios --cookie secret -S mix run --no-compile
    # para habilitar -it
    stdin_open: true
    tty: true
    user: "${DOCKER_UID}:${DOCKER_GID}"

  pagos:
    image: elixir:otp-27-alpine
    container_name: pagos
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      SERVER_TO_RUN: Libremarket.Pagos.Server
      MIX_HOME: /app/mix_home
      HEX_HOME: /app/hex_home
      CLOUDAMQP_URL: ${CLOUDAMQP_URL}
    command: iex --sname pagos --cookie secret -S mix run --no-compile
    # para habilitar -it
    stdin_open: true
    tty: true
    user: "${DOCKER_UID}:${DOCKER_GID}"